// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3kWYsz7pZ3qk5by6QxdJb4pWLTKnCME8',
    appId: '1:702966691379:android:20b8bb0bf349359f3b1546',
    messagingSenderId: '702966691379',
    projectId: 'rental-app-1b937',
    storageBucket: 'rental-app-1b937.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HB3NHWovUERTUNtH5flMTRGjOHPg3iE',
    appId: '1:702966691379:ios:1862091aa121188e3b1546',
    messagingSenderId: '702966691379',
    projectId: 'rental-app-1b937',
    storageBucket: 'rental-app-1b937.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcj7NYj8WUbJxxb5SJnpvZyQWLRd-01E4',
    appId: '1:702966691379:web:801bb5a546abd1903b1546',
    messagingSenderId: '702966691379',
    projectId: 'rental-app-1b937',
    authDomain: 'rental-app-1b937.firebaseapp.com',
    storageBucket: 'rental-app-1b937.firebasestorage.app',
    measurementId: 'G-5T3GGKHDH3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HB3NHWovUERTUNtH5flMTRGjOHPg3iE',
    appId: '1:702966691379:ios:1862091aa121188e3b1546',
    messagingSenderId: '702966691379',
    projectId: 'rental-app-1b937',
    storageBucket: 'rental-app-1b937.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcj7NYj8WUbJxxb5SJnpvZyQWLRd-01E4',
    appId: '1:702966691379:web:f18a733b636657b53b1546',
    messagingSenderId: '702966691379',
    projectId: 'rental-app-1b937',
    authDomain: 'rental-app-1b937.firebaseapp.com',
    storageBucket: 'rental-app-1b937.firebasestorage.app',
    measurementId: 'G-XY432JPN7D',
  );

}